# Generated by Django 5.0.14 on 2026-09-02 20:35

from django.conf import settings
from django.db import migrations, models


def backfill_rut_documents(apps, schema_editor):
    Paciente = apps.get_model('pacientes', 'Paciente')
    seen = set()
    for paciente in Paciente.objects.exclude(rut='').order_by('id').iterator():
        normalized = ''.join(char for char in paciente.rut.upper() if char.isalnum())
        if len(normalized) < 7 or len(normalized) > 9 or not normalized[:-1].isdigit():
            continue
        total = 0
        multiplier = 2
        for char in reversed(normalized[:-1]):
            total += int(char) * multiplier
            multiplier = 2 if multiplier == 7 else multiplier + 1
        result = 11 - (total % 11)
        expected = '0' if result == 11 else 'K' if result == 10 else str(result)
        key = (paciente.psicologo_id, normalized)
        if normalized[-1] != expected or key in seen:
            continue
        seen.add(key)
        paciente.tipo_documento = 'RUT'
        paciente.numero_documento = paciente.rut
        paciente.documento_normalizado = normalized
        paciente.save(
            update_fields=['tipo_documento', 'numero_documento', 'documento_normalizado']
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_paciente_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='documento_normalizado',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='paciente',
            name='numero_documento',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_documento',
            field=models.CharField(choices=[('RUT', 'RUT chileno'), ('PASAPORTE', 'Pasaporte'), ('OTRO', 'Otro documento')], default='RUT', max_length=15),
        ),
        migrations.RunPython(backfill_rut_documents, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(condition=models.Q(('documento_normalizado', ''), _negated=True), fields=('psicologo', 'tipo_documento', 'documento_normalizado'), name='paciente_documento_unico_por_psicologo'),
        ),
    ]
