# Generated by Django 5.0.14 on 2026-09-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_paciente_documento_normalizado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentimientoInformado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Consentimiento Informado para Atención Psicológica', max_length=255)),
                ('contenido', models.TextField(help_text='Texto completo del consentimiento redactado.')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Enviado / Pendiente de firma'), ('FIRMADO', 'Firmado digitalmente'), ('RECHAZADO', 'Rechazado')], db_index=True, default='BORRADOR', max_length=20)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('enlace_firma', models.URLField(blank=True, default='', max_length=500)),
                ('email_destino', models.EmailField(blank=True, default='', max_length=254)),
                ('email_enviado', models.BooleanField(default=False)),
                ('email_error', models.TextField(blank=True, default='')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('firma_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('firma_rut', models.CharField(blank=True, default='', max_length=30)),
                ('firma_imagen', models.TextField(blank=True, default='', help_text='Data URL base64 de la firma gráfica')),
                ('firma_ip', models.CharField(blank=True, default='', max_length=60)),
                ('firma_user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='pacientes.paciente')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos_emitidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consentimiento Informado',
                'verbose_name_plural': 'Consentimientos Informados',
                'ordering': ['-created_at'],
            },
        ),
    ]
