# Generated by Django 5.0.14 on 2026-07-08 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_google_calendar_sync'),
        ('pacientes', '0006_paciente_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agendacita',
            name='origen_reserva',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('PUBLICA_PACIENTE_EXISTENTE', 'Reserva pública — paciente existente'), ('PUBLICA_PACIENTE_NUEVO', 'Reserva pública — paciente nuevo')], default='MANUAL', max_length=30),
        ),
        migrations.AddField(
            model_name='agendacita',
            name='reserva_publica_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AgendaBloqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, default='', max_length=200)),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_bloqueos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bloqueo de agenda',
                'verbose_name_plural': 'Bloqueos de agenda',
                'ordering': ['inicio'],
            },
        ),
        migrations.CreateModel(
            name='AgendaPerfilPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre_publico', models.CharField(max_length=200)),
                ('subtitulo_publico', models.CharField(blank=True, default='', max_length=200)),
                ('descripcion_publica', models.TextField(blank=True, default='')),
                ('duracion_minutos', models.PositiveIntegerField(default=60)),
                ('anticipacion_minima_horas', models.PositiveIntegerField(default=12)),
                ('ventana_reserva_dias', models.PositiveIntegerField(default=30)),
                ('acepta_pacientes_nuevos', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('psicologo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_perfil_publico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil público de agenda',
                'verbose_name_plural': 'Perfiles públicos de agenda',
            },
        ),
        migrations.CreateModel(
            name='AgendaReservaPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_paciente', models.CharField(choices=[('EXISTENTE', 'Paciente existente'), ('NUEVO', 'Paciente nuevo')], max_length=20)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_publica', to='agenda.agendacita')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_publicas', to='pacientes.paciente')),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='agenda.agendaperfilpublico')),
            ],
            options={
                'verbose_name': 'Reserva pública',
                'verbose_name_plural': 'Reservas públicas',
            },
        ),
        migrations.CreateModel(
            name='AgendaDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_disponibilidad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disponibilidad',
                'verbose_name_plural': 'Disponibilidades',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('psicologo', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
