# Generated by Django 5.0.14 on 2026-07-10 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_agendacita_origen_reserva_and_more'),
    ]

    operations = []
