# Generated by Django 5.0.14 on 2026-09-02 20:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_agendaperfilpublico_instrucciones_reserva'),
        ('pacientes', '0007_paciente_documento_normalizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaperfilpublico',
            name='anticipacion_cambios_horas',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='agendareservapublica',
            name='codigo_reserva',
            field=models.CharField(blank=True, db_index=True, max_length=24, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='agendareservapublica',
            name='documento_digest',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='agendareservapublica',
            name='email_confirmacion',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='agendareservapublica',
            name='tipo_documento',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='agendareservapublica',
            name='ultima_gestion_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendareservapublica',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='AgendaReservaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREADA', 'Creada'), ('REPROGRAMADA', 'Reprogramada'), ('CANCELADA', 'Cancelada')], max_length=20)),
                ('actor', models.CharField(choices=[('PACIENTE', 'Paciente'), ('PSICOLOGO', 'Psicólogo'), ('SISTEMA', 'Sistema')], max_length=20)),
                ('inicio_anterior', models.DateTimeField(blank=True, null=True)),
                ('fin_anterior', models.DateTimeField(blank=True, null=True)),
                ('inicio_nuevo', models.DateTimeField(blank=True, null=True)),
                ('fin_nuevo', models.DateTimeField(blank=True, null=True)),
                ('estado_anterior', models.CharField(blank=True, default='', max_length=30)),
                ('estado_nuevo', models.CharField(blank=True, default='', max_length=30)),
                ('motivo', models.CharField(blank=True, default='', max_length=300)),
                ('version', models.PositiveIntegerField()),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='agenda.agendareservapublica')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgendaVerificacionReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_paciente', models.CharField(choices=[('EXISTENTE', 'Paciente existente'), ('NUEVO', 'Paciente nuevo')], max_length=20)),
                ('tipo_documento', models.CharField(max_length=15)),
                ('documento_digest', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('codigo_hash', models.CharField(max_length=64)),
                ('expira_at', models.DateTimeField()),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('verificada_at', models.DateTimeField(blank=True, null=True)),
                ('consumida_at', models.DateTimeField(blank=True, null=True)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verificaciones_reserva', to='pacientes.paciente')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificaciones_reserva', to='agenda.agendaperfilpublico')),
            ],
        ),
        migrations.AddConstraint(
            model_name='agendareservaevento',
            constraint=models.UniqueConstraint(condition=models.Q(('request_id', ''), _negated=True), fields=('reserva', 'request_id'), name='reserva_evento_request_unico'),
        ),
    ]
