# Generated by Django 5.0.14 on 2026-09-02 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPsicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notificaciones', models.EmailField(blank=True, default='', max_length=254)),
                ('email_notificaciones_verificado_at', models.DateTimeField(blank=True, null=True)),
                ('email_notificaciones_pendiente', models.EmailField(blank=True, default='', max_length=254)),
                ('email_verificacion_hash', models.CharField(blank=True, default='', max_length=64)),
                ('email_verificacion_expira_at', models.DateTimeField(blank=True, null=True)),
                ('email_verificacion_intentos', models.PositiveSmallIntegerField(default=0)),
                ('rut_profesional', models.CharField(blank=True, default='', max_length=12)),
                ('especialidad_clinica', models.CharField(blank=True, default='', max_length=180)),
                ('registro_profesional', models.CharField(blank=True, default='', max_length=80)),
                ('telefono_profesional', models.CharField(blank=True, default='', max_length=30)),
                ('modalidad_atencion', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('ONLINE', 'Online'), ('HIBRIDA', 'Presencial y online')], default='HIBRIDA', max_length=15)),
                ('comuna', models.CharField(blank=True, default='', max_length=100)),
                ('direccion_consulta', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_psicologo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
