# Generated by Django 5.0.14 on 2026-09-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_codigoverificacionregistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpsicologo',
            name='tutorial_visto',
            field=models.BooleanField(default=False),
        ),
    ]
