# Generated by Django 5.0.14 on 2026-10-02 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuentas', '0003_perfilpsicologo_tutorial_visto'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroConsumoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[('CHAT_CLINICO', 'Chat Clínico'), ('EVALUACION_TEST', 'Evaluación / Test'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('modelo', models.CharField(default='deepseek-chat', max_length=50)),
                ('tokens_prompt', models.PositiveIntegerField(default=0)),
                ('tokens_completion', models.PositiveIntegerField(default=0)),
                ('tokens_total', models.PositiveIntegerField(default=0)),
                ('costo_estimado_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Consumo IA',
                'verbose_name_plural': 'Registros de Consumo IA',
                'ordering': ['-created_at'],
            },
        ),
    ]
