# Generated by Django 5.0.14 on 2026-06-05 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0005_ficha_clinica_ampliada'),
        ('sesiones', '0007_alter_sesion_origen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionAsignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_slug', models.CharField(db_index=True, max_length=80)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('enlace_generado', models.URLField(blank=True, default='', max_length=500)),
                ('email_destino', models.EmailField(max_length=254)),
                ('mensaje_email', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('COMPLETADO', 'Completado'), ('EXPIRADO', 'Expirado'), ('ERROR_ENVIO', 'Error de envío')], db_index=True, default='PENDIENTE', max_length=20)),
                ('email_enviado', models.BooleanField(default=False)),
                ('email_error', models.TextField(blank=True, default='')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_asignadas', to='pacientes.paciente')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_asignadas', to=settings.AUTH_USER_MODEL)),
                ('sesion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_asignada', to='sesiones.sesion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestas', models.JSONField(default=dict)),
                ('puntajes', models.JSONField(default=dict)),
                ('interpretacion', models.JSONField(default=dict)),
                ('observacion_ia', models.TextField(blank=True, default='')),
                ('estado_ia', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('GENERADA', 'Generada'), ('SIN_CONFIGURACION', 'Sin configuración'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('error_ia', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='evaluaciones.evaluacionasignada')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
