# Generated by Django 5.0.14 on 2026-09-02 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_agendaperfilpublico_anticipacion_cambios_horas_and_more'),
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionemail',
            name='evento_reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_email', to='agenda.agendareservaevento'),
        ),
        migrations.AlterField(
            model_name='notificacionemail',
            name='tipo',
            field=models.CharField(choices=[('BIENVENIDA', 'Bienvenida'), ('RESERVA_PACIENTE', 'Reserva para paciente'), ('RESERVA_PSICOLOGO', 'Reserva para psicólogo'), ('REPROGRAMACION_PACIENTE', 'Reprogramación para paciente'), ('REPROGRAMACION_PSICOLOGO', 'Reprogramación para psicólogo'), ('CANCELACION_PACIENTE', 'Cancelación para paciente'), ('CANCELACION_PSICOLOGO', 'Cancelación para psicólogo')], max_length=30),
        ),
    ]
