# Generated by Django 5.0.14 on 2026-05-13 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField(auto_now_add=True)),
                ('duracion_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('audio_path', models.CharField(blank=True, default='', max_length=500)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('notas_sesion', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['-fecha_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TranscripcionSegmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('inicio_segundo', models.FloatField()),
                ('fin_segundo', models.FloatField()),
                ('hablante', models.CharField(choices=[('PSICOLOGO', 'Psicólogo'), ('PACIENTE', 'Paciente')], max_length=20)),
                ('texto', models.TextField()),
                ('texto_original', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentos', to='sesiones.sesion')),
            ],
            options={
                'ordering': ['sesion', 'orden'],
            },
        ),
    ]
