# Generated by Django 5.0.14 on 2026-06-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0004_speaker_identification_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='captions_buffer',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sesion',
            name='plataforma_virtual',
            field=models.CharField(blank=True, choices=[('GOOGLE_MEET', 'Google Meet'), ('ZOOM', 'Zoom')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sesion',
            name='url_reunion',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='origen',
            field=models.CharField(choices=[('AUDIO', 'Audio'), ('DOCUMENTO_EXTERNO', 'Documento externo'), ('VIRTUAL', 'Sesión virtual')], default='AUDIO', max_length=30),
        ),
    ]
