# Generated by Django 5.0.14 on 2026-06-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0006_numero_sesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='origen',
            field=models.CharField(choices=[('AUDIO', 'Audio'), ('DOCUMENTO_EXTERNO', 'Documento externo'), ('VIRTUAL', 'Sesión remota'), ('TEST_PSICOLOGICO', 'Test psicológico')], default='AUDIO', max_length=30),
        ),
    ]
