# Generated by Django 5.0.14 on 2026-09-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0007_alter_sesion_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='estado_videollamada',
            field=models.CharField(choices=[('CREADA', 'Creada'), ('EN_CURSO', 'En curso'), ('FINALIZADA', 'Finalizada')], default='CREADA', max_length=20),
        ),
        migrations.AddField(
            model_name='sesion',
            name='token_sala',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='plataforma_virtual',
            field=models.CharField(blank=True, choices=[('GOOGLE_MEET', 'Google Meet'), ('ZOOM', 'Zoom'), ('PSICONEX', 'Psiconex Meet')], max_length=20, null=True),
        ),
    ]
