# Generated by Django 5.0.14 on 2026-09-04 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('error', 'Reporte de Error (Bug)'), ('mejora', 'Sugerencia de Mejora'), ('felicitacion', 'Felicitación / Reconocimiento'), ('consulta', 'Consulta o Pregunta')], default='mejora', max_length=20, verbose_name='Tipo de Feedback')),
                ('modulo', models.CharField(choices=[('general', 'General / Interfaz'), ('pacientes', 'Pacientes / Ficha Clínica'), ('sesiones', 'Sesiones y Transcripción'), ('agenda', 'Agenda y Citas'), ('tests', 'Tests Psicológicos'), ('facturacion', 'Facturación / Boletas SII'), ('suscripcion', 'Mi Suscripción'), ('perfil', 'Mi Perfil / Configuración')], default='general', max_length=30, verbose_name='Módulo relacionado')),
                ('severidad', models.CharField(choices=[('baja', 'Baja — Inconveniente estético o menor'), ('media', 'Media — Función lenta o con falla parcial'), ('alta', 'Alta — Dificulta significativamente el trabajo'), ('critica', 'Crítica — Bloqueo total o pérdida de datos')], default='media', max_length=20, verbose_name='Severidad / Urgencia')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título o Asunto')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('pasos_reproducir', models.TextField(blank=True, default='', verbose_name='Pasos para reproducir (en errores)')),
                ('impacto_mejora', models.CharField(blank=True, default='', max_length=100, verbose_name='Impacto estimado de la mejora')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='feedback_adjuntos/%Y/%m/', verbose_name='Captura o Archivo adjunto')),
                ('url_origen', models.CharField(blank=True, default='', max_length=500, verbose_name='URL o Pantalla origen')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='Navegador y Sistema Operativo')),
                ('resolucion_pantalla', models.CharField(blank=True, default='', max_length=50, verbose_name='Resolución de pantalla')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('en_revision', 'En revisión'), ('resuelto', 'Resuelto'), ('descartado', 'Descartado')], default='nuevo', max_length=20, verbose_name='Estado de atención')),
                ('respuesta_admin', models.TextField(blank=True, default='', verbose_name='Respuesta del equipo de soporte')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('resuelto_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks_respondidos', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reporte de Feedback / Error',
                'verbose_name_plural': 'Reportes de Feedback y Errores',
                'ordering': ['-created_at'],
            },
        ),
    ]
